---
- name: Clone the repo and copy lab script
  ansible.builtin.command: "{{ item }}"
  loop:
    - sudo git clone https://github.com/opentraining-labs-customizations/satellite-bfx-support.git /opt/satellite-bfx-support/
    - sudo cp /opt/satellite-bfx-support/lab /usr/local/bin/
    - sudo chmod +x /usr/local/bin/lab

- name: Install the ansible-galaxy collection
  ansible.builtin.command: "sudo ansible-galaxy collection install -r /opt/satellite-bfx-support/requirements.yml -p /usr/share/ansible/collections/"
